variables:
  FOLDER: "/opt/sm_frontend"
  
stages:
  - deploy


deploy:
  stage: deploy
  tags:
    - deploy_shell
  script:
    - export
    #clean
    - if [ -d "$FOLDER" ]; then sudo rm -rf $FOLDER; fi
    #create
    - sudo mkdir $FOLDER
    - sudo chmod 777 $FOLDER
    - sudo cp -rf $CI_PROJECT_DIR/* $FOLDER
    - sudo chmod -R 777 $FOLDER
    - cd $FOLDER
    - sudo npm run build
  only:
    - main
    - dev
