variables:
  FOLDER: "/opt/sm_frontend"
  
stages:
  - deploy


deploy:
  stage: deploy
  tags:
    - deploy_shell
  script:
    - sudo su
    - export
    #clean
    - if [ -d "$FOLDER" ]; then rm -rf $FOLDER; fi
    #create
    - mkdir $FOLDER
    - chmod 777 $FOLDER
    - cp -rf $CI_PROJECT_DIR/* $FOLDER
    - chmod -R 777 $FOLDER
    - cd $FOLDER
    - npm run build
  only:
    - main
    - dev
